DROP TABLE EMPLOYERS IF EXISTS;
CREATE TABLE EMPLOYERS (
  ID               INT NOT NULL,
  NAME             VARCHAR(45),
  SURNAME          VARCHAR(45),
  BIRTHDAY         DATE,
  SALARY           INT
);

DROP SEQUENCE GEN_EMPLOYERS_ID IF EXISTS;
CREATE SEQUENCE GEN_EMPLOYERS_ID START WITH 60;